#color codes must have '&' and NOT any other symbol.

server_name: 'Test Minecraft server'

line8: '&a&lPLAYER'
line7: '&a » &7Online&8: &fN/A'
line6: '&b&lBLUE'
line5: '&b » &7Money&8: &fN/A'
line4: '&d&lPINK'
line3: '&d » &7PinkText&8: &fN/A'
line2: '&c&lSERVER'
line1: '&c » &7Server IP&8: &fN/A'
line0: '&c » &7Version&8: &f0.0.3'